### ISSUE TITLE
This example project should not require unsafe settings

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoBasicExample#57]
A little reminder re. the discussions about Goldmark.

This example should run fine with:

* Unsafe = false
* Inline shortcodes turned off

This project is supposed to be basic.

**Comment by onedrawingperday** [comment]
I have just sent #58 to address your concerns above.

The biggest change is the removal the sample post for Math Typesetting with KaTex since it is impossible to showcase it without Inline Shorcodes.

Unless you decide to enable: https://github.com/litao91/goldmark-mathjax

If you are OK then feel free to merge the PR.

I only have one remaining question that I didn't see in the new Docs:
Is there some kind of a global config setting for `footnoteReturnLinkContents` with Goldmark like there was with Blackfriday?

In

**Comment by onedrawingperday** [comment]
This issue also depends on https://github.com/gohugoio/hugo/issues/6544

**Comment by onedrawingperday** [comment]
Actually I have just discovered that Blackfriday is no longer needed to display Math Typesetting in Hugo Theme demos (better late than never I suppose).

So really there is no critical need about adding Goldmark Math Extensions (would be nice) as things work as they are set up right now.

@bep I have just removed the `mmark` content file from this repo in https://github.com/gohugoio/hugoBasicExample/commit/c4afa25a5a336ef44e869e9d1aea494a55994b6c

Also the themeSite was upgraded to use Goldmark instead of Blackfriday in https://github.com/gohugoio/hugoThemesSite/commit/854653f51625aa5ea389bbb1a2ffd6eb91977cea 

Hope that you realize that the need for the Goldmark `unsafe` flag and the Inline Shorcodes are needed to display the various Hugo features in the content files of theme demos at the Hugo Themes Showcase.

If you are OK with the above, then perhaps this issue should be closed.

**Comment by onedrawingperday** [comment]
The [latest Hugo Themes deploy](https://app.netlify.com/sites/hugothemes/deploys/5ec8343c9a633ef6eafa1a23) was a success with the latest changes.

So now the Hugo Themes website no longer needs mmark or Blackfriday.

All sample content files (including the one for Math Typesetting with KaTeX) render fine with Goldmark.

**Comment by sephore** [comment]
Is it just me, or the Math Typesetting example with Goldmark isn't making a distinction between inline and block?

**Comment by onedrawingperday** [comment]
@sephore 
Your question is out of place in this issue.

If you want to discuss your question then open a new issue and also make sure to provide a proper description of what you are referring to.

**Comment by skyfaller** [comment]
Hi folks, I just want to point out that `<cite>` is stripped out with safe settings. The `<cite>` tag appears in https://github.com/gohugoio/hugoBasicExample/blob/master/content/post/markdown-syntax.md#blockquote-with-attribution :
```markdown
#### Blockquote with attribution

> Don't communicate by sharing memory, share memory by communicating.<br>
> — <cite>Rob Pike[^1]</cite>
```

This file appears in all of the theme demos.
