### ISSUE TITLE
If this is a test, what are the criteria?

### ISSUE THREAD

**Issue by tvendelin** [gohugoio/hugoBasicExample#62]
If this project is meant to _test_ a theme before submitting it to Hugo themes repo, it would also make sense to provide criteria, as to the test has passed or not. Examples:

- Quite a few "test cases" end up in blocking RAW HTML code. What am I supposed to make of that? That hardly means my theme is "broken", as RAW HTML handling is defined in project configuration.

- My theme relies on `pygmentsUseClasses = true` et al. The test project doesn't, and so inline styling is applied. As a result, the appearance is a bit ugly. Is it acceptable to instruct the user to configure the project accordingly?

**Comment by digitalcraftsman** [comment]
Hello Toomas,

based on your question I assume you're asking prior of a theme submussion to www.github.com/gohugoio/hugoThemes, right? It might help to know a bit more about the context of your question, i.e. what you're trying to do.

The hugoBasicExample is used in place of the exampleSite directory for theme demos on www.themes.gohugo.io if the latter one is not provided. The setup in this repository meant to be minimal while covering a wide range of themes as possible. 

> My theme relies on pygmentsUseClasses = true et al. The test project doesn't, and so inline styling is applied. As a result, the appearance is a bit ugly. Is it acceptable to instruct the user to configure the project accordingly?

This repo isn't a static framework and can't cover all corner cases, especially when themes require a custom setup or configuration. Of course it is acceptable to let users configure the project according to your instructions. Pygments is likely configured the way it is because most of the users might use Hugo's built-in syntax highlighter Chroma nowadays.

--- 

In case you're planning to submit a new theme it's also possible submit a config file in the exampleSite directory to tweak a theme demo. In case your theme is more complex custom content can be used as well to cirumvent issues arising due to limitations of the hugoBasicExample.

**Comment by tvendelin** [comment]
Hi there, and thanks for quick response!

I'm just trying to make my theme "standard-compliant". I think you might be a tick more explicit about what makes a theme to pass into submission stage. 

You could, for instance, add a page to a project to test against the installation defaults. It shouldn't then contain any elements that require non-default configuration to work properly. This would be a useful indicator. For instance, I've discovered that tables without styling look ugly and fixed it.

Then, you might say: now run a server with _this_ config, and see how your theme performs with `<abbr>`, `<mark>`, etc. 

So, is it then OK to invite user to recursively clone a project repository that includes my theme as a git submodule?
