### ISSUE TITLE
Update demo content for themes

### ISSUE THREAD

**Issue by digitalcraftsman** [gohugoio/hugoBasicExample#9]
This basic example uses outdated docs as demo content. It's also widely used by other themes and as default content for themes on the theme site.

It should be replaced with more neutral content, i.e. a page that explains the basics of Markdown to show how elements of the website like headers, paragraphs, images and tables look with a certain theme.

@rdwatters

**Comment by Hanzei** [comment]
I looked for markdown explanations and found two:
- https://spec.commonmark.org/
- https://daringfireball.net/projects/markdown/syntax

I don`t know if we are allowed to use there text for this repository. So I ask them about the license. (See commonmark/CommonMark-site#12)

**Comment by onedrawingperday** [comment]
Due to enforcing this repo's `contentDir` with https://github.com/gohugoio/hugoThemes/pull/547 in theme demos on the Hugo showcase, now several themes have missing content due to various reasons.

So I am assigning this issue to myself. 

- I will be looking into overhauling the content directory of this repository and expanding it to accommodate themes that use Page Bundles and complex -but very popular- themes such as Academic.

- Also I will be addressing the concerns raised here and in #7 about outdated Hugo Documentation by removing it.

- Also I am in favor of displaying:
> the basics of Markdown to show how elements of the website like headers, paragraphs, images and tables look with a certain theme

There will be some Pull Requests coming around the end of February.
